GCPAuditLogs
| where MethodName =~ 'google.iam.admin.v1.CreateServiceAccountKey'
| extend result = parse_json(todynamic(AuthorizationInfo))[0]['granted']
| where result =~ "true"
| project-away result
| extend ServiceAccountID = split(parse_json(todynamic(AuthorizationInfo))[0]['resource'], '/')[3]
| extend UserAgent = parse_json(todynamic(RequestMetadata))['callerSuppliedUserAgent']
| where UserAgent notcontains "google-api-go-client"
| extend IPCustomEntity = parse_json(todynamic(RequestMetadata))['callerIp']
| extend AccountCustomEntity = PrincipalEmail